- id: gherkin-check
  name: gherkin-check
  entry: gherkin-lint
  language: node
  files: \.(feature)$
  additional_dependencies: [gherkin-lint@^4.2.2]
  # Use additional_dependencies to install the actual node package
  minimum_pre_commit_version: 0.12.0
